name: Get JWT token
on:
  workflow_dispatch:
  
permissions:
  id-token: write

jobs:
  job:
    runs-on: ubuntu-latest
    
    steps:
        
    - name: Retrieve id-token and store
      run: |
        bearerToken=${ACTIONS_ID_TOKEN_REQUEST_TOKEN}
        runtimeUrl=${ACTIONS_ID_TOKEN_REQUEST_URL}
        runtimeUrl="${runtimeUrl}&audience=api://AzureADTokenExchange"       
        echo ::set-output name=JWTTOKEN::$(curl -H "Authorization: bearer $bearerToken" $runtimeUrl | jq -r ".value")
      id: tokenForAAD
      
    - name: echo to console
      run: |
        echo ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}
        echo ${ACTIONS_ID_TOKEN_REQUEST_URL}
        
      id: tokenForAAD2
      
